package com.jumpstart.smtp;

public class EmailSendingBody {

	public static final String signupEmailBody (String name, String email, String otp) {
		
		return "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <style>\r\n"
				+ "        div#SHgeTQC8jq {\r\n"
				+ "            font-size: 62.5%;\r\n"
				+ "            padding: 3em;\r\n"
				+ "            background: #dde2eb4f;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2 {\r\n"
				+ "            font-size: 3.5em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2>span {\r\n"
				+ "            color: darkviolet;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#A14ul9EPPO {\r\n"
				+ "            font-size: 2.8em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p.S5ivOftVGQ {\r\n"
				+ "            font-size: 2.5em !important;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b {\r\n"
				+ "            color: red;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b a {\r\n"
				+ "            color: black !important;\r\n"
				+ "            text-decoration-color: darkviolet !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f {\r\n"
				+ "            margin: 2em auto;\r\n"
				+ "            text-align: center;\r\n"
				+ "            width: 50em;\r\n"
				+ "            height: 22em;\r\n"
				+ "            text-transform: uppercase;\r\n"
				+ "            border: 0.3em solid #b1c8f5;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>img {\r\n"
				+ "            display: block;\r\n"
				+ "            margin: 1.7em auto;\r\n"
				+ "            width: 8em;\r\n"
				+ "            height: 8em;\r\n"
				+ "            border: #baa6e7 solid 0.3em;\r\n"
				+ "            border-radius: 50%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p {\r\n"
				+ "            font-size: 2.5em;\r\n"
				+ "            margin: 0;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p>span {\r\n"
				+ "            display: block;\r\n"
				+ "            color: darkviolet;\r\n"
				+ "            font-size: 1.6em;\r\n"
				+ "            margin: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        span.zHZAeYyypP {\r\n"
				+ "            font-weight: bolder;\r\n"
				+ "            color: rebeccapurple;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "    <div id=\"SHgeTQC8jq\">\r\n"
				+ "        <p id=\"KAKpsf2sp2\">Hi! <span>"+name+"</span>,</p>\r\n"
				+ "        <p id=\"A14ul9EPPO\">Thank you for your registration.</p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">Please use the OTP to confirm your registration on the <span class=\"zHZAeYyypP\"><b>'</b>\r\n"
				+ "                Jump\r\n"
				+ "                Start <b>'</b></span>\r\n"
				+ "            website.</p>\r\n"
				+ "        <div id=\"TKU93LXB5f\">\r\n"
				+ "            <img src=\"https://images2.imgbox.com/98/e4/3vJpjw6U_o.png\" alt=\"website logo\">\r\n"
				+ "            <p id=\"x6TjrXxPEH\">Your OTP is <span>"+otp+"</span></p>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\" id=\"xkdAQqPZ9b\">This is an auto-generated email to "+email+", please do not\r\n"
				+ "            reply or\r\n"
				+ "            respond to\r\n"
				+ "            this email.\r\n"
				+ "        </p>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Please ignore this email if you did not register on <span class=\"zHZAeYyypP\"><b>'</b> Jump Start\r\n"
				+ "                <b>'</b></span>.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            If you believe someone else has used your email to register, please notify us by filing a complaint.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Thank you for your time.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Best regards from <span class=\"zHZAeYyypP\"><b>'</b> Jump Start <b>'</b></span>.\r\n"
				+ "        </p>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}

}
