package com.jumpstart.smtp;

import java.util.Date;

public class EmailSendingBody {

	public static final String signupEmailBody (String name, String email, String otp, Date validation) {
		
		return "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <style>\r\n"
				+ "        div#SHgeTQC8jq {\r\n"
				+ "            font-size: 62.5%;\r\n"
				+ "            padding: 3em;\r\n"
				+ "            background: #dde2eb4f;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2 {\r\n"
				+ "            font-size: 3.5em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2>span {\r\n"
				+ "            color: darkviolet;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#A14ul9EPPO {\r\n"
				+ "            font-size: 2.8em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p.S5ivOftVGQ {\r\n"
				+ "            font-size: 2.5em !important;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b {\r\n"
				+ "            color: red;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b a {\r\n"
				+ "            color: black !important;\r\n"
				+ "            text-decoration-color: darkviolet !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f {\r\n"
				+ "            margin: 2em auto;\r\n"
				+ "            text-align: center;\r\n"
				+ "            width: 50em;\r\n"
				+ "            max-width: 100%;\r\n"
				+ "            min-height: 22em;\r\n"
				+ "            text-transform: uppercase;\r\n"
				+ "            border: 0.3em solid #b1c8f5;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>img {\r\n"
				+ "            display: block;\r\n"
				+ "            margin: 1.7em auto;\r\n"
				+ "            width: 8em;\r\n"
				+ "            height: 8em;\r\n"
				+ "            border: #baa6e7 solid 0.3em;\r\n"
				+ "            border-radius: 50%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p {\r\n"
				+ "            font-size: 2.5em;\r\n"
				+ "            margin: 0;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p>span {\r\n"
				+ "            display: block;\r\n"
				+ "            color: darkviolet;\r\n"
				+ "            font-size: 1.6em;\r\n"
				+ "            margin: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p#x7TjrXoPEH {\r\n"
				+ "            font-weight: bolder;\r\n"
				+ "            font-size: 1.4em;\r\n"
				+ "            text-transform: none;\r\n"
				+ "            margin: 2em auto 0em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p#x7TjrXoPEH>span {\r\n"
				+ "            color: #baa6e7;\r\n"
				+ "            color: #b1c8f5;\r\n"
				+ "            color: red;\r\n"
				+ "            text-transform: none;\r\n"
				+ "            font-size: 1em;\r\n"
				+ "            display: inline;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        span.zHZAeYyypP {\r\n"
				+ "            font-weight: bolder;\r\n"
				+ "            color: rebeccapurple;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "    <div id=\"SHgeTQC8jq\">\r\n"
				+ "        <p id=\"KAKpsf2sp2\">Hi! <span>"+name+"</span>,</p>\r\n"
				+ "        <p id=\"A14ul9EPPO\">Thank you for your registration.</p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">Please use the OTP to confirm your registration on the <span class=\"zHZAeYyypP\"><b>'</b>\r\n"
				+ "                Jump\r\n"
				+ "                Start <b>'</b></span>\r\n"
				+ "            website.</p>\r\n"
				+ "        <div id=\"TKU93LXB5f\">\r\n"
				+ "            <img src=\"https://images2.imgbox.com/89/c5/xPz7zFNI_o.png\" alt=\"website logo\">\r\n"
				+ "            <p id=\"x6TjrXxPEH\">Your OTP is <span>"+otp+"</span></p>\r\n"
				+ "            <p id=\"x7TjrXoPEH\">Valid till <span>"+validation+"</span></p>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\" id=\"xkdAQqPZ9b\">This is an auto-generated email to "+email+", please do not\r\n"
				+ "            reply or\r\n"
				+ "            respond to\r\n"
				+ "            this email.\r\n"
				+ "        </p>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Please ignore this email if you did not register on <span class=\"zHZAeYyypP\"><b>'</b> Jump Start\r\n"
				+ "                <b>'</b></span>.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            If you believe someone else has used your email to register, please notify us by filing a complaint.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Thank you for your time.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Best regards from <span class=\"zHZAeYyypP\"><b>'</b> Jump Start <b>'</b></span>.\r\n"
				+ "        </p>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}
	
	
	
	public static final String resetEmailBody (String name, String email, String otp, Date validation) {
		
		return "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <style>\r\n"
				+ "        div#SHgeTQC8jq {\r\n"
				+ "            font-size: 62.5%;\r\n"
				+ "            padding: 3em;\r\n"
				+ "            background: #dde2eb4f;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2 {\r\n"
				+ "            font-size: 3.5em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#KAKpsf2sp2>span {\r\n"
				+ "            color: darkviolet;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#A14ul9EPPO {\r\n"
				+ "            font-size: 2.8em;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p.S5ivOftVGQ {\r\n"
				+ "            font-size: 2.5em !important;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b {\r\n"
				+ "            color: red;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p#xkdAQqPZ9b a {\r\n"
				+ "            color: black !important;\r\n"
				+ "            text-decoration-color: darkviolet !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f {\r\n"
				+ "            margin: 2em auto;\r\n"
				+ "            text-align: center;\r\n"
				+ "            width: 50em;\r\n"
				+ "            max-width: 100%;\r\n"
				+ "            min-height: 22em;\r\n"
				+ "            text-transform: uppercase;\r\n"
				+ "            border: 0.3em solid #b1c8f5;\r\n"
				+ "            border-radius: 1em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>img {\r\n"
				+ "            display: block;\r\n"
				+ "            margin: 1.7em auto;\r\n"
				+ "            width: 8em;\r\n"
				+ "            height: 8em;\r\n"
				+ "            border: #baa6e7 solid 0.3em;\r\n"
				+ "            border-radius: 50%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p {\r\n"
				+ "            font-size: 2.5em;\r\n"
				+ "            margin: 0;\r\n"
				+ "            color: black;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p>span {\r\n"
				+ "            display: block;\r\n"
				+ "            color: darkviolet;\r\n"
				+ "            font-size: 1.6em;\r\n"
				+ "            margin: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p#x7TjrXoPEH {\r\n"
				+ "            font-weight: bolder;\r\n"
				+ "            font-size: 1.4em;\r\n"
				+ "            text-transform: none;\r\n"
				+ "            margin: 2em auto 0em;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        div#TKU93LXB5f>p#x7TjrXoPEH>span {\r\n"
				+ "            color: #baa6e7;\r\n"
				+ "            color: #b1c8f5;\r\n"
				+ "            color: red;\r\n"
				+ "            text-transform: none;\r\n"
				+ "            font-size: 1em;\r\n"
				+ "            display: inline;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        span.zHZAeYyypP {\r\n"
				+ "            font-weight: bolder;\r\n"
				+ "            color: rebeccapurple;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "    <div id=\"SHgeTQC8jq\">\r\n"
				+ "        <p id=\"KAKpsf2sp2\">Hi! <span>"+name+"</span>,</p>\r\n"
				+ "        <p id=\"A14ul9EPPO\">It looks like you have a problem logging into your profile.</p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">Please use the OTP to confirm your identity for\r\n"
				+ "            resetting your password on the <span class=\"zHZAeYyypP\"><b>'</b>\r\n"
				+ "                Jump\r\n"
				+ "                Start <b>'</b></span>\r\n"
				+ "            website.</p>\r\n"
				+ "        <div id=\"TKU93LXB5f\">\r\n"
				+ "            <img src=\"https://images2.imgbox.com/89/c5/xPz7zFNI_o.png\" alt=\"website logo\">\r\n"
				+ "            <p id=\"x6TjrXxPEH\">Your OTP is <span>"+otp+"</span></p>\r\n"
				+ "            <p id=\"x7TjrXoPEH\">Valid till <span>"+validation+"</span></p>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\" id=\"xkdAQqPZ9b\">This is an auto-generated email to "+email+", please do not\r\n"
				+ "            reply or\r\n"
				+ "            respond to\r\n"
				+ "            this email.\r\n"
				+ "        </p>\r\n"
				+ "\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            If you didn't request to reset your password, someone else might try to log in to your <span\r\n"
				+ "                class=\"zHZAeYyypP\"><b>'</b> Jump Start\r\n"
				+ "                <b>'</b></span> account.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Do not worry; your account is still safe. But we would like you to change the password immediately.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Thank you for your time.\r\n"
				+ "        </p>\r\n"
				+ "        <p class=\"S5ivOftVGQ\">\r\n"
				+ "            Best regards from <span class=\"zHZAeYyypP\"><b>'</b> Jump Start <b>'</b></span>.\r\n"
				+ "        </p>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}





	public static final String passwordResetNotificationBody (String name, String email, String url, Date validation) {
	
	return "<html>\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <style>\r\n"
			+ "        div#SHgeTQC8jq {\r\n"
			+ "            font-size: 62.5%;\r\n"
			+ "            padding: 3em;\r\n"
			+ "            background: #dde2eb4f;\r\n"
			+ "            border-radius: 1em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#KAKpsf2sp2 {\r\n"
			+ "            font-size: 3.5em;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#KAKpsf2sp2>span {\r\n"
			+ "            color: darkviolet;\r\n"
			+ "\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#A14ul9EPPO {\r\n"
			+ "            font-size: 2.8em;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p.S5ivOftVGQ {\r\n"
			+ "            font-size: 2.5em !important;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#xkdAQqPZ9b {\r\n"
			+ "            color: red;\r\n"
			+ "            font-weight: bold;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#xkdAQqPZ9b a {\r\n"
			+ "            color: black !important;\r\n"
			+ "            text-decoration-color: darkviolet !important;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f {\r\n"
			+ "            margin: 2em auto;\r\n"
			+ "            text-align: center;\r\n"
			+ "            max-width: fit-content;\r\n"
			+ "            min-height: 20em;\r\n"
			+ "            border: 0.3em solid #b1c8f5;\r\n"
			+ "            border-radius: 1em;\r\n"
			+ "            padding: 2em;\r\n"
			+ "            word-wrap: break-word;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>img {\r\n"
			+ "            display: block;\r\n"
			+ "            margin: 1.7em auto;\r\n"
			+ "            width: 8em;\r\n"
			+ "            height: 8em;\r\n"
			+ "            border: #baa6e7 solid 0.3em;\r\n"
			+ "            border-radius: 50%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p {\r\n"
			+ "            font-size: 2.5em;\r\n"
			+ "            margin: 0;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "        span.zHZAeYyypP {\r\n"
			+ "            font-weight: bolder;\r\n"
			+ "            color: rebeccapurple;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "        a#fKU93LXB5T {\r\n"
			+ "            display: inline-block;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            color: darkviolet;\r\n"
			+ "            font-size: 2em;\r\n"
			+ "            border: #b1c8f5 .1em solid;\r\n"
			+ "            padding: .7em;\r\n"
			+ "            border-radius: 5em;\r\n"
			+ "            margin: 1.2em auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p.J5lNR6N4gK {\r\n"
			+ "            width: 100%;\r\n"
			+ "            text-align: center;\r\n"
			+ "            border-bottom: .1em solid #b1c8f5;\r\n"
			+ "            line-height: 0em;\r\n"
			+ "            margin: 1em auto 2em !important;\r\n"
			+ "            font-size: 1.8em;\r\n"
			+ "            font-weight: bolder;\r\n"
			+ "            text-transform: uppercase;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p.J5lNR6N4gK>span {\r\n"
			+ "            padding: 0 .8em;\r\n"
			+ "            color: black;\r\n"
			+ "            background: #b1c8f5;\r\n"
			+ "            border: #b1c8f5 .1em solid;\r\n"
			+ "            border-radius: 5em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p#x7TjrXoPEH {\r\n"
			+ "            font-weight: bolder;\r\n"
			+ "            font-size: 1.4em;\r\n"
			+ "            text-transform: none;\r\n"
			+ "            margin: 2em auto 0em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p#x7TjrXoPEH>span {\r\n"
			+ "            color: #baa6e7;\r\n"
			+ "            color: #b1c8f5;\r\n"
			+ "            color: red;\r\n"
			+ "            text-transform: none;\r\n"
			+ "            font-size: 1em;\r\n"
			+ "            display: inline;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <div id=\"SHgeTQC8jq\">\r\n"
			+ "        <p id=\"KAKpsf2sp2\">Hi! <span>"+name+"</span>,</p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">Your <span class=\"zHZAeYyypP\"><b>'</b>\r\n"
			+ "                Jump\r\n"
			+ "                Start <b>'</b></span> account's password has been changed.</p>\r\n"
			+ "\r\n"
			+ "        <p class=\"S5ivOftVGQ\">If you did not make this request, you can follow the link below to revert the change. If\r\n"
			+ "            you require more\r\n"
			+ "            assistance you can contact our support team at <span class=\"zHZAeYyypP\">support@jumpstart.com</span></p>\r\n"
			+ "\r\n"
			+ "        <div id=\"TKU93LXB5f\">\r\n"
			+ "            <img src=\"https://images2.imgbox.com/89/c5/xPz7zFNI_o.png\" alt=\"website logo\">\r\n"
			+ "\r\n"
			+ "            <a id=\"fKU93LXB5T\" href=\"http://localhost:3000/users/account-retriving/password-is-reverting-for/"+url+"\"\r\n"
			+ "                target=\"_blank\" rel=\"noopener noreferrer\">Revert The Password Change</a>\r\n"
			+ "            <p class=\"J5lNR6N4gK\"><span>or</span></p>\r\n"
			+ "            <p id=\"x6TjrXxPEH\">\r\n"
			+ "                http://localhost:3000/users/account-retriving/password-is-reverting-for/<span>"+url+"</span></p>\r\n"
			+ "            <p id=\"x7TjrXoPEH\">Valid till <span>"+validation+"</span></p>\r\n"
			+ "        </div>\r\n"
			+ "\r\n"
			+ "        <p class=\"S5ivOftVGQ\" id=\"xkdAQqPZ9b\">This is an auto-generated email to "+email+", please do not\r\n"
			+ "            reply or\r\n"
			+ "            respond to\r\n"
			+ "            this email.\r\n"
			+ "        </p>\r\n"
			+ "\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            If you didn't reset your password, someone else have changed it on <span class=\"zHZAeYyypP\"><b>'</b> Jump\r\n"
			+ "                Start\r\n"
			+ "                <b>'</b></span>.\r\n"
			+ "        </p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            We would like you to change the password immediately.\r\n"
			+ "        </p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            Thank you for your time.\r\n"
			+ "        </p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            Best regards from <span class=\"zHZAeYyypP\"><b>'</b> Jump Start <b>'</b></span>.\r\n"
			+ "        </p>\r\n"
			+ "    </div>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>";
	}




	public static final String userQueryResponseBody (String name, String queryId, String response, String respondent, String email, String queries) {
	
	return "<html>\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <style>\r\n"
			+ "        div#SHgeTQC8jq {\r\n"
			+ "            font-size: 62.5%;\r\n"
			+ "            padding: 3em;\r\n"
			+ "            border-radius: 1em;\r\n"
			+ "            background: #dde2eb4f;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#KAKpsf2sp2 {\r\n"
			+ "            font-size: 3.5em;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#KAKpsf2sp2>span {\r\n"
			+ "            color: darkviolet;\r\n"
			+ "\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#A14ul9EPPO {\r\n"
			+ "            font-size: 2.8em;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p.S5ivOftVGQ {\r\n"
			+ "            font-size: 2.5em !important;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#xkdAQqPZ9b {\r\n"
			+ "            color: red;\r\n"
			+ "            font-weight: bold;\r\n"
			+ "            margin-bottom: 5em !important;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p#xkdAQqPZ9b a {\r\n"
			+ "            color: black !important;\r\n"
			+ "            text-decoration-color: darkviolet !important;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f {\r\n"
			+ "            margin: 2em auto;\r\n"
			+ "            text-align: center;\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            min-height: 22em;\r\n"
			+ "            border: 0.3em solid #b1c8f5;\r\n"
			+ "            border-radius: 1em;\r\n"
			+ "            padding: 1.5em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>img {\r\n"
			+ "            display: block;\r\n"
			+ "            margin: 1.7em auto;\r\n"
			+ "            width: 8em;\r\n"
			+ "            height: 8em;\r\n"
			+ "            border: #baa6e7 solid 0.3em;\r\n"
			+ "            border-radius: 50%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p {\r\n"
			+ "            font-size: 2.5em;\r\n"
			+ "            margin: 0;\r\n"
			+ "            color: black;\r\n"
			+ "            text-align: justify;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p#x6TjrXxPEH {\r\n"
			+ "            text-align: end;\r\n"
			+ "            font-size: 1.8em;\r\n"
			+ "            margin-top: 2em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        div#TKU93LXB5f>p>span {\r\n"
			+ "            display: inline-block;\r\n"
			+ "            color: darkviolet;\r\n"
			+ "            margin: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        span.zHZAeYyypP {\r\n"
			+ "            font-weight: bolder;\r\n"
			+ "            color: rebeccapurple;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p.J5lNR6N4gK {\r\n"
			+ "            width: 100%;\r\n"
			+ "            text-align: center;\r\n"
			+ "            border-bottom: .2em solid #b1c8f5;\r\n"
			+ "            line-height: 0em;\r\n"
			+ "            margin: 3em auto;\r\n"
			+ "            font-size: 1.4em;\r\n"
			+ "            font-weight: bolder;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        p.J5lNR6N4gK>span {\r\n"
			+ "            background: white;\r\n"
			+ "            padding: .3em .8em;\r\n"
			+ "            color: rebeccapurple;\r\n"
			+ "            border: #b1c8f5 .1em solid;\r\n"
			+ "            border-radius: 5em;\r\n"
			+ "            font-size: 1.4em;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <div id=\"SHgeTQC8jq\">\r\n"
			+ "        <p id=\"KAKpsf2sp2\">Hi! <span>"+name+"</span>,</p>\r\n"
			+ "        <p id=\"A14ul9EPPO\">Thank you so much for your queries and time.</p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">Your quering id is : <span class=\"zHZAeYyypP\">"+queryId+"</span></p>\r\n"
			+ "\r\n"
			+ "        <p class=\"J5lNR6N4gK\"><span>Our Response</span></p>\r\n"
			+ "\r\n"
			+ "        <div id=\"TKU93LXB5f\">\r\n"
			+ "            <img src=\"https://images2.imgbox.com/89/c5/xPz7zFNI_o.png\" alt=\"website logo\">\r\n"
			+ "            <p>"+response+"</p>\r\n"
			+ "            <p id=\"x6TjrXxPEH\">Responded By - <span>"+respondent+"</span></p>\r\n"
			+ "        </div>\r\n"
			+ "\r\n"
			+ "        <p class=\"S5ivOftVGQ\" id=\"xkdAQqPZ9b\">You are receiving this mail because someone has use this (\r\n"
			+ "            "+email+" ) to contact us for this below query.\r\n"
			+ "        </p>\r\n"
			+ "\r\n"
			+ "        <p class=\"J5lNR6N4gK\"><span>Your Queries</span></p>\r\n"
			+ "\r\n"
			+ "        <div id=\"TKU93LXB5f\">\r\n"
			+ "            <img src=\"https://images2.imgbox.com/ab/09/lUUczJbw_o.png\" alt=\"user avtar logo\">\r\n"
			+ "            <p>"+queries+"</p>\r\n"
			+ "            <p id=\"x6TjrXxPEH\">Queried By - <span>"+name+"</span></p>\r\n"
			+ "        </div>\r\n"
			+ "\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            Feel free to contact us anytime on this email <span class=\"zHZAeYyypP\">support@jumpstart.com</span> or by\r\n"
			+ "            using the\r\n"
			+ "            contact form on the\r\n"
			+ "            website\r\n"
			+ "            <span class=\"zHZAeYyypP\">http://localhost:3000/help</span>\r\n"
			+ "        </p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            Please mention your response id <span class=\"zHZAeYyypP\">"+queryId+"</span> to get a fast response from us.\r\n"
			+ "        </p>\r\n"
			+ "        <p class=\"S5ivOftVGQ\">\r\n"
			+ "            Best regards from <span class=\"zHZAeYyypP\"><b>'</b> Jump Start Support Team <b>'</b></span>.\r\n"
			+ "        </p>\r\n"
			+ "    </div>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>";
	}

}
